### ISSUE TITLE
Release new version on PyPI

### ISSUE THREAD

**Issue by flyte** [eelcovv/LatLonCalc#1]
Hi, thanks for creating this library!

The [version on PyPI](https://pypi.python.org/pypi/LatLon) is pretty old (1.0.2) compared to what's in this repo. Would you be able to make a release so that it can be pip installed?

Cheers

**Comment by eelcovv** [comment]
Hi Flyte, I will see what I can do and can find the time for it. For now you can just install it with a reference to this git repo of course
Cheers

**Comment by drewsonne** [comment]
I'd also like to ask for a release. If you have `twine`, it's a two liner with:

```shell
python setup.py sdist bdist_wheel
twine upload dist/*
```

**Comment by danmichaelo** [comment]
The version at PyPI didn't work with python 3.8. For reference, here is how to install it now:

    pip install future git+git://github.com/eelcovv/LatLon

**Comment by eelcovv** [comment]
Tried to fix it tonight. The problem is, I original developper is not maintaining the package anymore and  not responding to emails. I am not allowed to push to the package LatLon, so I tried a new name LatLon3. Still not allowed. Don't know why. So I give up for now. Package is working now for python 3.8 in any case you want to follow up. I am not maintaining this anymore as well

**Comment by eelcovv** [comment]
A bit late, but finally I submitted this package under a new name to pypi: https://pypi.org/project/latloncalc/ 
The name latloncalc was needed as somebody else published my previous version of latlon3 for python3. My new version latloncalc has a better documentation and was published with tox, so tested for several python distributions (3.6, 3.7, 3.8, 3.9, 3.10)
